version: '3.4'

services:
  mongo:
    restart: 'no'
    image: mongo:4.2.0
    command: --serviceExecutor adaptive
    volumes:
      - mongodata:/data/db

  mgcli:
    restart: 'no'
    image: mongo:4.2.0
    depends_on:
      - mongo
    command: >
      sh -c 'mongo --host mongo '

  mongo-express:
    restart: 'no'
    image: mongo-express:0.49.0
    ports:
      - 8081:8081
    depends_on:
      - mongo

volumes:
  mongodata:
